language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import
script:
- make publish github
env:
  global:
    secure: OX78N+nlNoGEu0fpvHrQ3mfc/xsziWg73ds0tGIeFsSTf0fb3a73lJCXsQbU0ggP/XwlYYhAzEUmm6SV5vqR79hYxslrN7lw+z9ObuWSSv56oLgejudlZj4fmLjo9/1bN+U2LPQbFp5LQ4dGZcmubcXN2ltJN2CrGS6dUn8rMms=
before_install:
  - git submodule update --init --recursive
after_success: bash deploy.sh