language: python
branches:
  only:
  - pelican
install:
- pip install pelican Markdown ghp-import unidecode
script:
- make html
env:
  global:
    secure:  OUKQXR2BSM6wxH2zbDAeo5Uo8ozNpOFc0sQRHrWJK1DmWn5QYMY99gADdpyVvOwh3Anuq3gbqVn9Y8Q2SxfVKCQ0vPkvCF77fi5xeVVbBsI7WmqKeIJChdZ/vUKBKiwREqC9/9HuV947RyVV6RAVvlq4lBPvaFYks26wxa1CTew=
before_install:
  - git submodule update --init --recursive
after_success: bash deploy.sh